version: '2'

services:
  app:
    build: ./php
    volumes:
      - ./../:/var/www/html/my-site
    depends_on:
      - sqlserver
    working_dir: /var/www/html/my-site

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - 8008:80
    volumes_from:
      - app

  sqlserver:
    build: ./sqlserver
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Admin@12345
    ports:
      - 1433:1433
    volumes:
      - ms-sqlserver-data:/var/opt/mssql

volumes:
  ms-sqlserver-data:
    driver: local